config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy' 

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end

  resources :categories, only: [:new, :create, :show, :index]

  resources :users, only: [:show, :create, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include SlugableCtrembley
  
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true

  slugable_column :name

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include VoteableCtrembley

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  include VoteableCtrembley
  include SlugableCtrembley

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true

  slugable_column :title

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  include SlugableCtrembley

  has_many :posts
  has_many :comments
  has_many :votes

  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 5}

  slugable_column :username

  def is_admin?
    self.role == 'admin'
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :creator, foreign_key: :user_id, class_name: "User"
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :creator, scope: [:voteable_type, :voteable_id]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You must be logged in to perform that action."
      redirect_to root_path
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]
  before_action :require_admin, only: [:new, :create]

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(slug: params[:id])
    @posts = @category.posts.sort_by{|x| x.total_votes}.reverse
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "New Category Created!"
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || !current_user.is_admin?
      flash[:error] = "You do not have sufficient privileges to perform that action."
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
#need to define the post and comment objects here
#comments.create = User.first
before_action :require_user

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find_by(slug: params[:post_id])
    #@comment = @post.comments.build(comment_params)
    @comment.creator = current_user

    if @comment.save
      @post.comments << @comment #see above
      flash[:notice] = "Comment created successfully!"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(voteable: @comment, creator: current_user, vote: params[:vote])

    respond_to do |format|

      format.html do 

        if @vote.valid?
          flash[:notice] = "Vote counted"
        else
          flash[:error] = "You have already voted on this post."
        end
        redirect_to :back
      end

      format.js
    end

  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :can_edit?, only: [:edit, :update]



  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse
  end

  def show
    @comment = Comment.new
    respond_to do |format|
      format.html
      format.json do
        render json: @post
      end
      format.xml { render xml: @post }
    end
    
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:notice] = "Your post was created."
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit  
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Post updated successfully"
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|

      format.html do 

        if @vote.valid?
          flash[:notice] = "Vote counted"
        else
          flash[:error] = "You have already voted on this post."
        end
        redirect_to :back
      end

      format.js
    end

  end

  private

  def post_params
    #when permitting an array it needs to be in the form of permit(:category_ids [])
    params.require(:post).permit!
  end

  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def can_edit?
    if current_user != @post.creator && !current_user.is_admin?
      flash[:error] = "Sorry you can not perform that action."
      redirect_to post_path(@post)
    end 
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.where(username: params[:username]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Log in successful"
      redirect_to root_path
    else
      flash[:error] = "There was an error with your username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now logged out."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def new
    cant_register_after_login
    
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save 
      session[:user_id] = @user.id
      flash[:notice] = "Profile created!"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update    

    if @user.update(user_params)
      flash[:notice] = "Profile updated!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show

  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :time_zone)
  end

  def set_user
    @user = User.find_by(slug: params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:error] = "That action is not allowed"
      redirect_to root_path
    end
  end

  def cant_register_after_login
    if logged_in?
      flash[:error] = "You are all ready registered"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  #method to check if url starts_with?('http://'), if not prepend that to the front and return 
  def fix_url(url)
    if (url.starts_with?('http://') || url.starts_with?('https://'))
      return url
    else
       "http://#{url}"
    end
  end

  def fix_date(date)

    if logged_in? && !current_user.time_zone.blank?
      date = date.in_time_zone(current_user.time_zone)
    end

    date.strftime("%l:%M%P %Z on %D")
  end
end

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %></span>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: "All Categories" %>

<% @categories.each do |category| %>
  <div class='row'>
    <div class='span8 well'>
      <h4><%= link_to category.name, category_path(category) %></h4>
      <small>
        <span>
          <%= link_to("#{pluralize(category.posts.size, 'post')}", category_path(category)) %>
        </span>
      </small>
    </div>
  </div>
<% end %>

app/views/categories/new.html.erb
<% if @category.errors.any? %>
  <%= render 'shared/error_messages', obj: @category %>
<% end %>

<%= render 'shared/content_title', title: "Create a New Category" %>

<div class='well'>
  <%= form_for @category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br/>
    <%= f.submit "Create Category", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + " &raquo; #{@category.name}".html_safe %>

<%= render 'shared/content_title', title: header %>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>



<div class='row'>

  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>

      <br/>

        <span id='comment_<%= comment.id %>_votes'><%= "#{comment.total_votes} #{'vote'.pluralize(comment.total_votes)}" %></span>

      <br/>

      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method:'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>

    <% else %>

      <%= "#{comment.total_votes} #{'vote'.pluralize(comment.total_votes)}" %>

    <% end %>
  </div>

  <div class='well span8'>
    <em>
      <% if show_post %>
        "<%= comment.body %>" on <%= link_to comment.post.title, post_path(comment.post) %>
      <% else %>
        "<%= comment.body %>"
      <% end %>
    </em>
    <hr/>
    <p>
      <span class='quiet'>Posted by</span> <%= link_to comment.creator.username, user_path(comment.creator) %>
      <small>at <%= fix_date(comment.created_at) %></small>
    </p>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
	$("#comment_<%= @comment.id%>_votes").html("<%= @comment.total_votes %> <%= 'vote'.pluralize(@comment.total_votes) %>");
<% else %>
	alert("You have already voted on this comment.");
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>

  <div class='btn-group nav_item'>
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
    	Categories <span class='caret'></span>
    <% end %>
    
    <ul class='dropdown-menu'>
    	<% Category.all.each do |category| %>
    		<li><%= link_to category.name, category_path(category) %></li>
    	<% end %>

      <% if logged_in? && current_user.is_admin? %>
        <li class='divider'></li>

        <li>
          <%= link_to(new_category_path) do %>
            <i class="icon-plus"></i>
            New Category
          <% end %>
        </li>
      <% end %>

    </ul>
  </div>

  <% if logged_in? %>

    <div class='nav_item'>
      <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
    </div>

    <div class='btn-group nav_item'>
      <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        <%= current_user.username %><span class='caret'></span>
      <% end %>

      <ul class='dropdown-menu' %>
        <li>
          <%= link_to edit_user_path(current_user) do %>
            <i class='icon-pencil'></i>
            Edit Profile
          <% end %>
        </li>
        <li>
          <%= link_to user_path(current_user) do %>
            <i class='icon-user'></i>
            View Profile
          <% end %>
        </li>
        <li class='divider'></li>
        <li>
          <%= link_to logout_path do %>
            <i class='icon-circle-arrow-left'></i>
            Logout
          <% end %>
        </li>
      </ul>
    </div>

  <% else %>

    <div class='nav_item'>
      <%= link_to 'Register', register_path, class: 'btn btn-success btn-small' %>
    </div>

    <div class='nav_item'>
      <%= link_to 'Login', login_path, class: 'btn btn-small' %>
    </div>

  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <%= render 'shared/error_messages', obj: @post %>
<% end %>

<p>
  <% #div control-group was added to these in the solutuion %>
  <%= form_for @post do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br/>

    <%= f.label :url %>
    <%= f.text_field :url %>
    <br/>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>
    <br/>

    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
    <br/>
    <% #:category_ids: are the 'value', from a collection of Category, individual id and name %>

    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post',  class: "btn btn-primary") %> 
  <% end %>
  <% #select value requires [] for multiple, ex: <select> name=options[]</select> %>
</p>

app/views/posts/_post.html.erb
<div class='row'>	
  <div class='span0 well text-center'>
		<% if logged_in? %>
	    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
	      <i class='icon-arrow-up'></i>

	    <% end %>

	    <br/>

	    <span id='post_<%=post.slug%>_votes'><%= "#{post.total_votes} #{'vote'.pluralize(post.total_votes)}" %></span>

	    <br/>

	    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
	      <i class='icon-arrow-down'></i>
	    <% end %>

	  <% else %>

	    <%= "#{post.total_votes} #{'vote'.pluralize(post.total_votes)}" %>

	  <% end %>
	</div>

	<div class='well span8'>
		<p>
		  <%= render post.categories %>
		</p>

		<%= link_to (render 'shared/content_title', title: post.title), fix_url(post.url) %>

		<p>
		  <%= post.description %>
		</p>

		<% if logged_in? && (current_user == post.creator || current_user.is_admin?) %>

			<p>
			  <small><%= link_to "Edit Post", edit_post_path(post)%></small>
			</p>

		<% end %>

	  <hr/>

		<p>
		  <span class='quiet'>Posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
		  <small>at <%= fix_date(post.created_at) %></small>
		  
		</p>
		<small>
		  <span>
		    <%= link_to("#{pluralize(post.comments.size, 'comment')}", post_path(post)) %>
		  </span>
		</small>
	</div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: "Update your post!" %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <div class='row'>
      <%= render 'post', post: post %>
  </div>
<% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: "Create a new post!" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class='row' >
  <%= render 'posts/post', post: @post %>
</div> 



<% #comment form: form_for [@post, @comment] ...  need the parent object for nested resources %>

<% if logged_in? %>

  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/error_messages', obj: @comment %>
    <%= f.label :body, "Add a comment" %>
    <%= f.text_area :body %>
    <br/>
    <%= f.submit "Add Comment", class: 'btn btn-success' %>
  <% end %>

<% end %>

<h5>Comments:</h5>

<% @post.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
	$("#post_<%= @post.slug%>_votes").html("<%= @post.total_votes %> <%= 'vote'.pluralize(@post.total_votes) %>");
<% else %>
	alert("You have already voted on this post.");
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
</p>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-error"> 
	 	<h5>Oops looks like something isn't quite right:</h5>
	  <% #had a span8 after alert-error in solutions %>
	  <ul>
	    <% obj.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <%= render 'shared/error_messages', obj: @user %>
<% end %>

<div class='well'>
  <%= form_for @user do |f| %>

    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :time_zone %>
    <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, default: Time.zone.name %>

    <hr/>

    <%= f.submit @user.new_record? ? "Register" : "Update Profile", class: 'btn btn-primary' %>
    
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/content_title', title: "Update your profile." %>

<h5>Change your user name or password.</h5>

<%= render 'form' %>

app/views/users/new.html.erb
<%= render 'shared/content_title', title: "Register for Postit!" %>

<h5>Please enter a username and password:</h5>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "You are viewing #{@user.username}'s Profile!" %>

<div class='well'>
  <dl class='dl-horizontal'>
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
  </dl>

  <dl class='dl-horizontal'>
    <dt>Time Zone:</dt>
    <dd><%= @user.time_zone %></dd>
  </dl> 
</div>

<h5><%= "#{@user.username}'s Activity:" %></h5>

<ul class='nav nav-tabs'>
  <li class='<%= 'active' if params[:tab].nil? %>'>
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'comments' %>'>
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <% @user.posts.each do |post| %>
    <%= render 'posts/post', post: post %>

  <% end %>

<% else %>
  <% @user.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment, show_post: true %>
  <% end %>
<% end %>